// Cargo.toml
[package]
name = "tag_cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
id3 = "1.13.1"
walkdir = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
simple_logger = "4.3.0"
anyhow = "1.0"
